version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - admin_db

  admin_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - admin_db

  admin_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@root123
      MYSQL_ROOT_PASSWORD: Root@root123
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3307:3306
